# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: corporationXYZ
    build: .
    command: gunicorn -b 0.0.0.0:5000 corporationXYZ.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/corporationXYZ.db
    volumes:
      - ./corporationXYZ:/code/corporationXYZ
      - ./db/:/db/
    ports:
      - "5000:5000"
