"""empty message

Revision ID: 136fd0f5c046
Revises: 3c403aee5d08
Create Date: 2020-10-13 11:09:13.905653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136fd0f5c046'
down_revision = '3c403aee5d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('to', sa.String(length=1000), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('bodyContent', sa.String(length=255), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    # ### end Alembic commands ###
