"""empty message

Revision ID: df58af93d9f2
Revises: 136fd0f5c046
Create Date: 2020-10-13 11:11:22.722020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df58af93d9f2'
down_revision = '136fd0f5c046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'email', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.drop_column('email', 'user_id')
    # ### end Alembic commands ###
